### ISSUE TITLE
Assignment 1 Complete!

### ISSUE THREAD

**Issue by amurulid** [VIS-2129-F2020/amurulidhar-vis#1]

**Comment by bauranov** [comment]
Good work. Here are some comments:
- Line 38: Add "message=FALSE" to suppress messages in HTML. 
- Line 45: When all the dots are clustered together, it makes sense to make them transparent so the ones in the back can also be seen. You can set this by specifying alpha parameter: geom_point(alpha=0.5).
- Plots 8,9,10,11: Make sure to add names of the variables to the legends. 

Keep up the good work!
