### ISSUE TITLE
Assignment 2 Completed

### ISSUE THREAD

**Issue by amurulid** [VIS-2129-F2020/amurulidhar-vis#2]

**Comment by bauranov** [comment]
Great work! Here are some comments:
-  I would encourage you to explore color palettes other than Viridis. 
- Sometimes it makes sense to add names of the countries to the map. You can do that with geom_label() or geom_text().
- Please add a link to your HTML file in the issue comment. You can do that with https://vis-2129-f2020.github.io/amurulidhar-vis/filename where *filename* is the name of your HTML file. Thanks
